from enum import Enum

from pydantic import BaseModel, Field


class DecompiledFunction(BaseModel):
    name: str
    code: str
    signature: str | None = None
    error: str | None = None
    # Rich response fields (populated when include_* flags are set)
    callees: "ListFunctionCallsResponse | None" = None
    referenced_strings: list[str] | None = None
    xrefs: list["CrossReferenceInfo"] | None = None


class DisassembledFunction(BaseModel):
    name: str
    entry: str = Field(..., description="entry-point address, e.g. '0x00401000'")
    signature: str | None = None
    listing: str = Field(
        ...,
        description=(
            "flat assembly text, one 'address: mnemonic operands ; comment' line per instruction"
        ),
    )
    instruction_count: int
    error: str | None = None


class ProgramBasicInfo(BaseModel):
    name: str
    analysis_complete: bool


class ProgramBasicInfos(BaseModel):
    programs: list[ProgramBasicInfo]


class ProgramInfo(BaseModel):
    name: str
    file_path: str | None = None
    load_time: float | None = None
    analysis_complete: bool
    metadata: dict
    code_indexed: bool
    strings_indexed: bool


class ListProgramsResponse(BaseModel):
    programs: list[ProgramInfo]


class OpenProgramInfo(BaseModel):
    name: str
    path: str
    current: bool
    analysis_complete: bool


class ListOpenProgramsResponse(BaseModel):
    programs: list[OpenProgramInfo]


class SkippedImport(BaseModel):
    path: str
    reason: str


class ImportBinaryResponse(BaseModel):
    requested_path: str
    queued_count: int
    queued_paths: list[str]
    skipped_count: int
    skipped: list[SkippedImport]
    message: str


class GotoResponse(BaseModel):
    program_name: str
    address: str
    success: bool


class RenameFunctionResponse(BaseModel):
    program_name: str
    address: str
    old_name: str
    new_name: str


class RenameVariableResponse(BaseModel):
    program_name: str
    function_name: str
    function_address: str
    variable_kind: str
    old_name: str
    new_name: str


class SetVariableTypeResponse(BaseModel):
    program_name: str
    function_name: str
    function_address: str
    variable_kind: str
    variable_name: str
    old_type: str
    new_type: str


class SetCommentResponse(BaseModel):
    program_name: str
    address: str
    comment: str
    comment_type: str


class CreateFunctionResponse(BaseModel):
    program_name: str
    name: str = Field(..., description="function name (autogenerated if no name was passed in)")
    entry_point: str
    body_size: int = Field(..., description="bytes Ghidra claimed for the new function body")


class DeleteFunctionResponse(BaseModel):
    program_name: str
    name: str = Field(..., description="name of the function that was deleted")
    entry_point: str


class SaveProgramResponse(BaseModel):
    program_name: str
    saved: bool


class SetFunctionPrototypeResponse(BaseModel):
    program_name: str
    name: str = Field(..., description="function name (post-update; prototype may rename it)")
    entry_point: str
    signature: str = Field(..., description="function signature after the prototype was applied")


class _StructFieldOpBase(BaseModel):
    """Internal base shared by struct-field operation responses."""

    program_name: str
    struct_name: str
    offset: int = Field(..., description="affected field's byte offset within the struct")
    struct_size: int = Field(..., description="struct's total size after the operation")


class AddStructFieldResponse(_StructFieldOpBase):
    """Response from `add_struct_field`."""


class SetStructFieldResponse(_StructFieldOpBase):
    """Response from `set_struct_field`."""


class DeleteStructFieldResponse(_StructFieldOpBase):
    """Response from `delete_struct_field`."""


class StructField(BaseModel):
    """A single field in a struct or union.

    `offset` is only honored by `create_struct_type`. For `create_union_type`
    it is ignored (unions always start each field at offset 0).
    """

    name: str
    type: str
    offset: int | None = Field(
        None, description="Explicit byte offset for struct layout; None appends"
    )


class CreateDataTypeResponse(BaseModel):
    program_name: str
    name: str
    size: int = Field(..., description="total size in bytes")


class DeleteDataTypeResponse(BaseModel):
    program_name: str
    name: str = Field(..., description="bare name of the data type that was deleted")
    path: str = Field(..., description="DTM path of the deleted type, e.g. '/MyLib/Foo'")
    kind: str = Field(
        ...,
        description=(
            "classification: struct/enum/union/array/pointer/typedef/function/primitive/other"
        ),
    )


class ImportCTypesResponse(BaseModel):
    program_name: str
    imported: list["DataTypeInfo"] = Field(
        ..., description="data types newly added to the DTM by this call"
    )
    skipped: list[str] = Field(
        ...,
        description=(
            "DTM paths of types that already existed and were preserved "
            "(only populated when replace=False)"
        ),
    )
    errors: list[str] = Field(
        ..., description="parser warnings / per-type failures encountered during the import"
    )


class ApplyDataTypeResponse(BaseModel):
    program_name: str
    address: str
    applied_size: int = Field(..., description="bytes actually applied at the address")


class RunInlineScriptResponse(BaseModel):
    program_name: str
    stdout: str
    stderr: str
    result_repr: str | None = Field(
        None, description="repr() of the `result` variable if the script assigned one"
    )
    committed: bool = Field(..., description="True if the Ghidra transaction was committed")
    error: str | None = None


class RunScriptResponse(BaseModel):
    program_name: str
    script: str = Field(..., description="script path or name as passed in by the caller")
    resolved_path: str = Field(..., description="absolute path of the file that was executed")
    stdout: str
    stderr: str
    result_repr: str | None = Field(
        None, description="repr() of the `result` variable if the script assigned one"
    )
    committed: bool = Field(..., description="True if the Ghidra transaction was committed")
    error: str | None = None


class ScriptJobHandle(BaseModel):
    """Returned by `run_script_async` / `run_inline_script_async`.

    The script begins running in a background worker; clients poll
    `poll_script_job(job_id)` to retrieve the result once status is
    terminal (`completed` or `failed`).
    """

    program_name: str
    job_id: str = Field(..., description="opaque id for polling via poll_script_job")
    status: str = Field(
        ..., description="initial state: 'queued' or 'running' (worker may have started already)"
    )
    submitted_at: float = Field(..., description="seconds-since-epoch the job was registered")


class ScriptJobStatus(BaseModel):
    """Returned by `poll_script_job`. Result fields are populated when
    `status` is terminal (`completed` or `failed`), otherwise they're None.
    """

    job_id: str
    program_name: str
    status: str = Field(
        ..., description="lifecycle state: 'queued' | 'running' | 'completed' | 'failed'"
    )
    submitted_at: float
    started_at: float | None = Field(None, description="when the worker picked up the job")
    completed_at: float | None = Field(None, description="when the job reached a terminal state")
    stdout: str | None = None
    stderr: str | None = None
    result_repr: str | None = Field(
        None, description="repr() of the script's `result` variable, if any"
    )
    committed: bool | None = Field(
        None, description="True if the Ghidra transaction was committed"
    )
    error: str | None = Field(
        None,
        description=(
            "exception message if the script raised, or any registry-level failure"
        ),
    )


class ExportInfo(BaseModel):
    name: str
    address: str


class ExportInfos(BaseModel):
    exports: list[ExportInfo]


class ImportInfo(BaseModel):
    name: str
    library: str


class ImportInfos(BaseModel):
    imports: list[ImportInfo]


class FunctionRef(BaseModel):
    name: str
    address: str


class ListFunctionCallsResponse(BaseModel):
    functions: list[FunctionRef]


class FunctionInfo(BaseModel):
    name: str
    address: str
    refcount: int = Field(..., description="number of cross-references to this function")
    is_thunk: bool
    is_external: bool
    is_user_defined: bool = Field(
        ...,
        description=(
            "True if the name was assigned by user/import; False for Ghidra autos like FUN_*"
        ),
    )


class SearchFunctionsResponse(BaseModel):
    functions: list[FunctionInfo]


class DataItemInfo(BaseModel):
    name: str = Field(
        ...,
        description="label of the data item; synthesized as 'DAT_<addr>' when no symbol exists",
    )
    address: str
    type: str = Field(..., description="data type name, e.g. 'char[16]', 'MyStruct', 'dword'")
    length: int = Field(..., description="bytes occupied at the address")
    refcount: int = Field(..., description="number of cross-references to this data item")


class SearchDataItemsResponse(BaseModel):
    data_items: list[DataItemInfo]


class CrossReferenceInfo(BaseModel):
    function_name: str | None = None
    from_address: str
    to_address: str
    type: str


class CrossReferenceInfos(BaseModel):
    target: str | None = None
    cross_references: list[CrossReferenceInfo]
    error: str | None = None


# Resolve forward reference for DecompiledFunction.xrefs
DecompiledFunction.model_rebuild()
# ImportCTypesResponse forward-references DataTypeInfo (defined below).


class SymbolInfo(BaseModel):
    name: str
    address: str
    type: str
    namespace: str
    source: str
    refcount: int
    external: bool


class SearchSymbolsResponse(BaseModel):
    symbols: list[SymbolInfo]


class SearchMode(str, Enum):
    """Search mode for code search."""

    SEMANTIC = "semantic"  # Vector similarity search
    LITERAL = "literal"  # Exact string match ($contains)


class SymbolKind(str, Enum):
    """Classifications for `search_symbols`. Pass a list of values to
    narrow the search; omit or pass ``null`` to include every symbol."""

    FUNCTIONS = "functions"  # only FUNCTION symbols
    GLOBALS = "globals"  # symbols in the global namespace, excluding functions
    LABELS = "labels"  # only LABEL-type symbols (code + data labels)


class DataTypeKind(str, Enum):
    """Classifications for `search_data_types`. Pass a list of values to
    narrow the search; omit or pass ``null`` to include every kind."""

    STRUCT = "struct"
    ENUM = "enum"
    UNION = "union"
    ARRAY = "array"
    POINTER = "pointer"
    TYPEDEF = "typedef"
    FUNCTION = "function"  # function signature (prototype) data types
    PRIMITIVE = "primitive"  # Ghidra built-in types (int, char, void, ...)


class DataTypeInfo(BaseModel):
    name: str
    kind: str = Field(
        ...,
        description=(
            "classification: struct/enum/union/array/pointer/typedef/function/primitive/other"
        ),
    )
    size: int | None = Field(
        None, description="byte length; None when Ghidra reports variable/undefined length"
    )
    path: str = Field(..., description="data-type manager path, e.g. '/MyCategory/MyStruct'")


class SearchDataTypesResponse(BaseModel):
    data_types: list[DataTypeInfo]


# ImportCTypesResponse references DataTypeInfo above — finalize the forward ref.
ImportCTypesResponse.model_rebuild()


class StructFieldDetail(BaseModel):
    offset: int = Field(..., description="byte offset within the struct")
    size: int
    type: str = Field(..., description="data type name (e.g. 'int', 'Point*')")
    name: str | None = Field(None, description="field name; None for unnamed components")


class GetStructLayoutResponse(BaseModel):
    program_name: str
    name: str
    path: str = Field(..., description="resolved DTM path, e.g. '/MyLib/Point'")
    size: int
    fields: list[StructFieldDetail]


class UnionFieldDetail(BaseModel):
    size: int
    type: str
    name: str | None = None


class GetUnionLayoutResponse(BaseModel):
    program_name: str
    name: str
    path: str
    size: int
    fields: list[UnionFieldDetail]


class GetEnumValuesResponse(BaseModel):
    program_name: str
    name: str
    path: str
    size: int
    values: dict[str, int]


class CodeSearchResult(BaseModel):
    function_name: str
    code: str
    similarity: float
    search_mode: SearchMode
    preview: str | None = None


class SearchCodeResponse(BaseModel):
    results: list[CodeSearchResult]
    query: str
    search_mode: SearchMode
    returned_count: int
    offset: int
    limit: int
    literal_total: int = Field(..., description="total literal matches")
    semantic_total: int = Field(..., description="estimated semantic matches")
    total_functions: int


class StringInfo(BaseModel):
    value: str
    address: str


class StringSearchResult(StringInfo):
    similarity: float


class SearchStringsResponse(BaseModel):
    strings: list[StringSearchResult]


class ReadBytesResponse(BaseModel):
    address: str
    size: int
    data: str = Field(..., description="hex string")


class CallGraphDirection(str, Enum):
    """Represents the direction of the call graph."""

    CALLING = "calling"
    CALLED = "called"


class CallGraphDisplayType(str, Enum):
    """Represents the display type of the call graph."""

    FLOW = "flow"
    FLOW_ENDS = "flow_ends"
    MIND = "mind"


class GenCallgraphResponse(BaseModel):
    function_name: str
    direction: CallGraphDirection
    display_type: CallGraphDisplayType
    graph: str = Field(..., description="MermaidJS graph string")
    mermaid_url: str
