"""Unit tests for GhidraTools.search_functions filter logic."""

from unittest.mock import Mock, patch

from pyghidra_mcp.models import FunctionInfo
from pyghidra_mcp.tools import GhidraTools


def _make_function_info(
    name: str,
    address: str,
    *,
    refcount: int = 0,
    is_thunk: bool = False,
    is_external: bool = False,
    is_user_defined: bool = True,
) -> FunctionInfo:
    return FunctionInfo(
        name=name,
        address=address,
        refcount=refcount,
        is_thunk=is_thunk,
        is_external=is_external,
        is_user_defined=is_user_defined,
    )


def _make_tools(function_infos: list[FunctionInfo]) -> GhidraTools:
    """Build a minimally-mocked GhidraTools whose iteration yields the given infos.

    We bypass FunctionManager entirely by patching ``_function_to_info`` and
    feeding fake "function" sentinels through ``getFunctions``.
    """
    sentinels = [Mock() for _ in function_infos]
    sentinel_to_info = dict(zip(sentinels, function_infos, strict=True))

    # Wire each sentinel so the include_thunks / include_externals
    # short-circuits (which read from func.isThunk() / func.isExternal())
    # see the matching predicate values.
    for sentinel, info in sentinel_to_info.items():
        sentinel.isThunk.return_value = info.is_thunk
        sentinel.isExternal.return_value = info.is_external

    fake_fm = Mock()
    fake_fm.getFunctions.return_value = sentinels

    program_info = Mock()
    program_info.program.getFunctionManager.return_value = fake_fm

    tools = GhidraTools.__new__(GhidraTools)
    tools.program_info = program_info
    tools.program = program_info.program
    tools.decompiler_pool = Mock()

    def _to_info(func):
        return sentinel_to_info[func]

    patcher = patch.object(GhidraTools, "_function_to_info", staticmethod(_to_info))
    patcher.start()
    return tools


def test_no_filters_returns_all_in_address_order():
    infos = [
        _make_function_info("main", "0x1000"),
        _make_function_info("helper", "0x2000"),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions()
    assert [f.name for f in results] == ["main", "helper"]


def test_query_filters_by_regex_on_name():
    infos = [
        _make_function_info("main", "0x1000"),
        _make_function_info("init_a", "0x2000"),
        _make_function_info("init_b", "0x3000"),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(query="^init_")
    assert {f.name for f in results} == {"init_a", "init_b"}


def test_min_refcount_filters_low_callers():
    infos = [
        _make_function_info("rare", "0x1000", refcount=1),
        _make_function_info("popular", "0x2000", refcount=42),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(min_refcount=10)
    assert [f.name for f in results] == ["popular"]


def test_max_refcount_filters_heavy_callers():
    infos = [
        _make_function_info("rare", "0x1000", refcount=1),
        _make_function_info("popular", "0x2000", refcount=42),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(max_refcount=10)
    assert [f.name for f in results] == ["rare"]


def test_user_defined_only_excludes_autogenerated():
    infos = [
        _make_function_info("main", "0x1000", is_user_defined=True),
        _make_function_info("FUN_002000", "0x2000", is_user_defined=False),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(user_defined_only=True)
    assert [f.name for f in results] == ["main"]


def test_include_thunks_false_skips_thunks():
    infos = [
        _make_function_info("main", "0x1000", is_thunk=False),
        _make_function_info("__stub", "0x2000", is_thunk=True),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(include_thunks=False)
    assert [f.name for f in results] == ["main"]


def test_include_externals_false_skips_externals():
    infos = [
        _make_function_info("main", "0x1000", is_external=False),
        _make_function_info("printf", "0x2000", is_external=True),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(include_externals=False)
    assert [f.name for f in results] == ["main"]


def test_offset_and_limit_paginate():
    infos = [_make_function_info(f"f{i}", f"0x{i:04x}") for i in range(10)]
    tools = _make_tools(infos)
    page = tools.search_functions(offset=3, limit=2)
    assert [f.name for f in page] == ["f3", "f4"]


def test_combined_filters_compose():
    infos = [
        _make_function_info("init_a", "0x1000", refcount=1, is_user_defined=True),
        _make_function_info("init_b", "0x2000", refcount=15, is_user_defined=True),
        _make_function_info("init_c", "0x3000", refcount=20, is_user_defined=False),
        _make_function_info("main", "0x4000", refcount=2, is_user_defined=True),
    ]
    tools = _make_tools(infos)
    results = tools.search_functions(
        query="^init_",
        min_refcount=10,
        user_defined_only=True,
    )
    assert [f.name for f in results] == ["init_b"]
